name: Build and Release Nezha Agent for MIPS

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      agent_ref:
        description: "nezhahq/agent 的分支/标签/提交（测试用，空则自动选择）"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    name: Build mips and mipsle
    runs-on: ubuntu-latest
    steps:
      - name: Resolve agent ref
        id: ref
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          REPO="nezhahq/agent"

          # 1) 手动输入优先
          CANDIDATE=""
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.agent_ref }}" ]; then
            CANDIDATE="${{ github.event.inputs.agent_ref }}"
          fi

          # 2) 其次尝试使用本仓库 Release 的标签名
          if [ -z "$CANDIDATE" ] && [ "${{ github.event_name }}" = "release" ] && [ -n "${{ github.event.release.tag_name }}" ]; then
            CANDIDATE="${{ github.event.release.tag_name }}"
          fi

          check_ref() {
            local ref="$1"
            if [ -z "$ref" ]; then return 1; fi
            if gh api -X GET "repos/$REPO/git/ref/tags/$ref" >/dev/null 2>&1; then return 0; fi
            if gh api -X GET "repos/$REPO/branches/$ref" >/dev/null 2>&1; then return 0; fi
            return 1
          }

          REF=""
          if check_ref "$CANDIDATE"; then
            REF="$CANDIDATE"
          else
            LATEST_TAG="$(gh api "repos/$REPO/releases/latest" -q .tag_name || true)"
            if check_ref "$LATEST_TAG"; then
              REF="$LATEST_TAG"
            else
              DEFAULT_BRANCH="$(gh api "repos/$REPO" -q .default_branch || echo main)"
              REF="$DEFAULT_BRANCH"
            fi
          fi
          echo "ref=$REF" >> "$GITHUB_OUTPUT"
          echo "Using nezhahq/agent ref: $REF"

      - name: Checkout nezhahq/agent
        uses: actions/checkout@v4
        with:
          repository: nezhahq/agent
          ref: ${{ steps.ref.outputs.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install upx
        run: |
          sudo apt-get update
          sudo apt-get install -y upx || sudo apt-get install -y upx-ucl

      - name: Build and compress (mips, mipsle)
        run: |
          set -euxo pipefail
          mkdir -p dist
          go mod download

          for ARCH in mips mipsle; do
            echo "==> Building $ARCH ..."
            CGO_ENABLED=0 GOOS=linux GOARCH=$ARCH GOMIPS=softfloat \
              go build \
                -trimpath \
                -tags "netgo,osusergo" \
                -gcflags "all=-l" \
                -ldflags "-s -w -buildid=" \
                -o main \
                cmd/agent/main.go

            OUT="dist/nezha-agent-linux-$ARCH"
            echo "==> UPX compress to $OUT ..."
            upx --best --ultra-brute -o "$OUT" main || upx --best -o "$OUT" main

            SIZE=$(stat -c%s "$OUT")
            echo "Built size: $SIZE bytes"
            if [ "$SIZE" -gt 5242880 ]; then
              echo "::error::Binary $OUT exceeds 5MB ($SIZE bytes)"
              exit 1
            fi

            rm -f main
            ls -lh "$OUT"
          done

      - name: Create checksums
        run: |
          (cd dist && sha256sum * > SHA256SUMS.txt)
          cat dist/SHA256SUMS.txt

      - name: Upload assets to current release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/nezha-agent-linux-mips
            dist/nezha-agent-linux-mipsle
            dist/SHA256SUMS.txt
          fail_on_unmatched_files: true
          tag_name: ${{ github.event.release.tag_name }}

      - name: Upload artifacts (manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nezha-agent-mips-build
          path: |
            dist/nezha-agent-linux-mips
            dist/nezha-agent-linux-mipsle
            dist/SHA256SUMS.txt
          if-no-files-found: error

    timeout-minutes: 30
